### ISSUE TITLE
warning message: 'name' not found

### ISSUE THREAD

**Issue by binary1230** [magfest-archive/mivs#41]
This line: 

```
def indie_games(self):
        return self.query(IndieGame).options(joinedload(IndieGame.studio), joinedload(IndieGame.reviews)).order_by('name').all()
```

Is causing this warning message to be printed on a fresh install:

```
/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/sql/compiler.py:572: SAWarning: Can't resolve label reference 'name'; converting to text() (this warning may be suppressed after 10 occurrences)
  util.ellipses_string(element.element))
```

I think it's because we are using text in the order_by() clause instead of a reference to something in the original query.

Here I think it may be because 'name' is a reference to a field in IndieStudio, but the sqlalchemy compiler at this stage might not have that in scope which means it doesn't know how to resolve as text.  Might have to explicity reference `studio.name` there, or something, since IndieStudio is loaded as a join

**Comment by binary1230** [comment]
Did some more reading and looks like we may need another .join() there to do this order_by() correctly.
http://docs.sqlalchemy.org/en/latest/orm/loading_relationships.html

For now, this doesn't look like it's hurting anything but will emit warnings, so we should prob fix it.

**Comment by EliAndrewC** [comment]
Ahhh yeah, instead of ``.order_by('name')`` we should instead be saying ``.order_by(IndieGame.name)`` since that's more unambiguous.
